import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFile } from "node:fs/promises";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const runtimeSourcePlugin = {
	name: "runtime-source",
	setup(build) {
		build.onResolve({ filter: /^virtual:(claude-chat-bridge-source|pi-agent-bridge-source|claude-code-cli-source)$/ }, (args) => ({
			path: args.path,
			namespace: "runtime-source",
		}));

		const buildBridgeSource = async (entryPoint, displayName) => {
			const bridgeBundle = await esbuild.build({
				entryPoints: [entryPoint],
				bundle: true,
				platform: "node",
				format: "esm",
				target: "node18",
				write: false,
				minify: prod,
				external: builtinModules.flatMap((moduleName) => [moduleName, `node:${moduleName}`]),
			});
			const bridgeSource = bridgeBundle.outputFiles[0]?.text;
			if (!bridgeSource) {
				throw new Error(`Failed to bundle ${displayName} source.`);
			}
			return bridgeSource;
		};

		build.onLoad({ filter: /^virtual:claude-chat-bridge-source$/, namespace: "runtime-source" }, async () => {
			return {
				contents: `export default ${JSON.stringify(await buildBridgeSource("scripts/claude-chat-bridge.mjs", "Claude bridge"))};`,
				loader: "js",
			};
		});

		build.onLoad({ filter: /^virtual:pi-agent-bridge-source$/, namespace: "runtime-source" }, async () => {
			return {
				contents: `export default ${JSON.stringify(await buildBridgeSource("scripts/pi-agent-bridge.mjs", "Pi bridge"))};`,
				loader: "js",
			};
		});

		build.onLoad({ filter: /^virtual:claude-code-cli-source$/, namespace: "runtime-source" }, async () => {
			const cliSource = await readFile("node_modules/@anthropic-ai/claude-agent-sdk/cli.js", "utf8");
			return {
				contents: `export default ${JSON.stringify(cliSource)};`,
				loader: "js",
			};
		});
	},
};

// Using symlink for hot reload:
// The test vault plugin folder can be symlinked to this project root:
// <vault>/.obsidian/plugins/ai-chat-sidebar -> <plugin-source>
// When you run `npm run dev`, changes are built to main.js in this folder,
// and Obsidian can hot-reload through the symlink.

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [runtimeSourcePlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
