import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

let pluginDir = "";
try {
	const envPath = path.resolve(process.cwd(), ".env");
	if (fs.existsSync(envPath)) {
		const envLines = fs.readFileSync(envPath, "utf8").split("\n");
		for (const line of envLines) {
			if (line.trim().startsWith("OBSIDIAN_PLUGIN_DIR=")) {
				pluginDir = line.substring(line.indexOf("=") + 1).trim();
				if (pluginDir.startsWith('"') && pluginDir.endsWith('"')) {
					pluginDir = pluginDir.substring(1, pluginDir.length - 1);
				} else if (pluginDir.startsWith("'") && pluginDir.endsWith("'")) {
					pluginDir = pluginDir.substring(1, pluginDir.length - 1);
				}
				break;
			}
		}
	} else {
		console.log("ℹ️  No .env file found at root. Skipping auto-copy.");
	}
} catch (e) {
	console.error("⚠️  Error reading .env file:", e.message);
}

const copyToObsidianPlugin = {
	name: "copy-to-obsidian",
	setup(build) {
		build.onEnd(() => {
			if (!pluginDir) {
				console.log("ℹ️  OBSIDIAN_PLUGIN_DIR is not set in .env. Skipping auto-copy.");
				return;
			}
			try {
				if (!fs.existsSync(pluginDir)) {
					console.log(`ℹ️  Creating directory: ${pluginDir}`);
					fs.mkdirSync(pluginDir, { recursive: true });
				}
				const filesToCopy = ["main.js", "manifest.json", "styles.css"];
				for (const file of filesToCopy) {
					if (fs.existsSync(file)) {
						fs.copyFileSync(file, path.join(pluginDir, file));
					}
				}
				const sourceScript = path.join("scripts", "claude-chat-bridge.mjs");
				const targetScriptDir = path.join(pluginDir, "scripts");
				if (!fs.existsSync(targetScriptDir)) {
					fs.mkdirSync(targetScriptDir, { recursive: true });
				}
				if (fs.existsSync(sourceScript)) {
					fs.copyFileSync(sourceScript, path.join(targetScriptDir, "claude-chat-bridge.mjs"));
				}
				console.log(`✅  Successfully copied plugin files to: ${pluginDir}`);
			} catch (e) {
				console.error("❌  Error copying files to Obsidian plugin directory:", e);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToObsidianPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
